### ISSUE TITLE
2018 P1 output format under-specified

### ISSUE THREAD

**Issue by RojerGS** [Dyalog/PracticeProblems#10]
For P1 from 2018, ["Oh Say Can You See"](https://problems.tryapl.org/psets/2018.html?goto=P1_Oh_Say_Can_You_See), the output is defined as

 > [...] an integer representing the number of skyscrapers that can be seen.

However, the test cases expect a 1-item vector.
I would like to know if the output should have been specified as a 1-item vector, or if the validator should be lenient (and how lenient) before committing a fix in a PR.

**Comment by abrudz** [comment]
The validation should clearly be with `≢` and not `⍴` but I think we should be lenient and accept any simple singleton.

**Comment by rikedyp** [comment]
fixed in 29e386e98ecc9dff4fb72f55b7025028a4b1ac98
