### ISSUE TITLE
2013-1 gives Internal Error for all solutions

### ISSUE THREAD

**Issue by rikedyp** [Dyalog/PracticeProblems#45]
https://problems.tryapl.org/psets/2013.html

![image](https://user-images.githubusercontent.com/9338369/197840038-2b93bc46-d056-4c4a-99ee-3283c6907f4b.png)

reported by @bpbecker

**Comment by abrudz** [comment]
Fixed in 3f57e5b1f00443a4f657928b18568e0bf7644501
